language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
python:
  - 2.7
matrix:
  fast_finish: true
before_install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
install:
  - bin/buildout annotate
  - bin/buildout
script:
  - bin/test
after_success:
  - bin/createcoverage --output-dir=parts/test/coverage
  - bin/pip install -q coveralls
  - bin/coveralls
notifications:
  email:
    - laurent.lasudry@affinitic.be
