os:
  - linux
dist: bionic
language: python

cache:
  pip: true
  directories:
  - eggs

python:
  - "2.7"
  - "3.6"
  - "3.7.5"
  - "3.7.6"
  - "3.8"

jobs:
  fast_finish: true
  allow_failures:
    - python: "3.6"
    - python: "3.8"

before_install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt

install:
  - bin/buildout annotate
  - bin/buildout

script:
  - bin/test

after_success:
  - bin/createcoverage --output-dir=parts/test/coverage
  - bin/pip install -q coveralls
  - bin/coveralls
